services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cronovan_db
      MYSQL_USER: rafael
      MYSQL_PASSWORD: 1234
    ports:
      - '3306:3306'
    # (this is just an example, not intended to be a production configuration)